# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-20 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170817_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_on']},
        ),
    ]
