# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170820_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, max_length=210)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
    ]
