# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170825_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
