# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170829_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_message',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
