# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_entry',
            name='body',
            field=models.TextField(),
        ),
    ]
