# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-20 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20170817_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed_entry',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Feed Entry', 'verbose_name_plural': 'Feed Entries'},
        ),
        migrations.AlterField(
            model_name='feed_entry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='feed_entry',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 20, 16, 54, 37, 821499)),
        ),
    ]
