# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20170820_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_entry',
            name='publish_date',
            field=models.DateField(default=b'2017-08-20 18:27:39'),
        ),
    ]
