# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20170820_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_entry',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
