# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-22 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20170821_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='belongs_to',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
