# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20170824_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='feed_entry',
            name='body',
            field=models.TextField(max_length=20),
        ),
    ]
